services:
    _defaults:
        autowire: true

    Depense\Module\User\Repository\UserRepository:
        arguments:
            $className: 'Depense\Module\User\Model\User'
    
    Depense\Module\User\Repository\UserOAuthRepository:
        arguments:
            $className: 'Depense\Module\User\Model\UserOAuth'
    
    Depense\Module\User\Repository\UserPreferenceRepository:
        arguments:
            $className: 'Depense\Module\User\Model\UserPreference'
