doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Module/User/Resources/config/doctrine'
                prefix: Depense\Module\User\Model
                alias: User
            Account:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Module/Account/Resources/config/doctrine'
                prefix: Depense\Module\Account\Model
                alias: Account
            Wallet:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Module/Wallet/Resources/config/doctrine'
                prefix: Depense\Module\Wallet\Model
                alias: Wallet
            Taxonomy:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Module/Taxonomy/Resources/config/doctrine'
                prefix: Depense\Module\Taxonomy\Model
                alias: Taxonomy
            Transaction:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Module/Transaction/Resources/config/doctrine'
                prefix: Depense\Module\Transaction\Model
                alias: Transaction
