depense_app:
    resource: ../../src/Web/Controller/App/
    type: annotation
    prefix: /app

depense_root:
    resource: ../../src/Web/Controller/Root/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
