services:
    _defaults:
        autowire: true
        autoconfigure: true

    Depense\Module\Resource\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Model/'
            - '../../Repository/'
