services:
    _defaults:
        autowire: true

    Depense\Module\Transaction\Repository\TransactionRepository:
        arguments:
            $className: 'Depense\Module\Transaction\Model\Transaction'
