imports:
    - { resource: services/repositories.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Depense\Module\Account\:
        resource: '../../'
        exclude:
            - '../../Resources/'
            - '../../Model/'
            - '../../Repository/'
